global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'scoms-local'
    environment: 'production'

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # SCOMS Application
  - job_name: 'scoms-app'
    static_configs:
      - targets: ['scoms-app:3000']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s
    honor_labels: true
    
  # Docker containers metrics via cAdvisor (if needed later)
  - job_name: 'docker'
    static_configs:
      - targets: []
    scrape_interval: 30s
