global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'scoms-local'
    environment: 'development'

rule_files:
  - 'alerts.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # SCOMS Application running locally
  - job_name: 'scoms-app-local'
    static_configs:
      - targets: ['host.docker.internal:3000']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s
    honor_labels: true
    params:
      environment: ['development']

  # Development Database Metrics (if postgres_exporter is added later)
  - job_name: 'postgres-dev'
    static_configs:
      - targets: []
    scrape_interval: 30s
